log:
  console:
    level: debug
db:
  driver: mysql
  user: isula
  password: isula
  name: isula
  server: localhost:3306
server:
  schema: https
  port: 443
  keyfile: server.key
  certfile: server.cert
  website: isula.org
storageload: static
storage:
  filesystem:
    rootdirectory: /tmp/idata
session:
  inmemory:
